FROM node:20-slim

WORKDIR /app

COPY front-end/ ./

RUN npm install -g pnpm

RUN pnpm install
RUN cd apps/web && pnpm build

ENV NEXT_PUBLIC_API_URL=http://localhost:5001

EXPOSE 3000

CMD ["sh", "-c", "cd apps/web && pnpm start"] 